<a href="https://colab.research.google.com/github/mokhivibes/ml_course_courseworks/blob/main/3Coursework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NumPy tezligini Python bilan solishtirib ko'ramiz
import numpy as np
import time

lst = list(range(1_000))
arr = np.array(lst)

#List
start = time.time()
lst2 = [x*2 for x in lst]
print("List:", time.time() - start)

#NumPy
start = time.time()
arr2 = arr*2
print("NumPy:", time.time() - start)

List: 0.00032401084899902344
NumPy: 0.0002200603485107422


In [ ]:
#NumPyda array yaratib ko'ramiz

a = np.array([1, 2, 3, 4, 5])
print(a[2]) #3
print(a * 2) # [2,4,6,8,10]

#Python list da *2 listni ikki marta takrorlaydi - NumPy esa har elementga qo'llaydi.

3
[ 2  4  6  8 10]


In [ ]:
#np.array()- eng asosiy, listdan yaratish
arr = np.array([1,2,3,4,5]) #=> 1D array
arr2d = np.array([[1,2,3,4], [5,6,7,8]]) #=> 2D array

arr2 = np.array(range(100))
print(arr2d)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#Tayyor to'ldirilgan array
nollar = np.zeros((5, 6)) # 5 qator, 6 ustun, hammasi 0
birlar = np.ones((3, 2)) # 3 qator, 2 ustun, hammasi 1
sakkizlar = np.full((2, 3), 8) # 2 qator, 3 ustun, hammasi 8
print(nollar)
print(birlar)
print(sakkizlar)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[8 8 8]
 [8 8 8]]


In [ ]:
#np.arang() va np.linspace()

a = np.arange(1, 11, 2) # 0 dan 10 gacha, qadam 2
#start, stop, qadam
print(a)
b = np.linspace(0, 14, 5) # 0 dan 10 gacha, 5 ta teng oraliq
#start, stop, nechta teng oraliqda
print(b)

[1 3 5 7 9]
[ 0.   3.5  7.  10.5 14. ]


In [ ]:
#np.random

np.random.seed(42)
a = np.random.rand(3, 3) # 0 va 1 orasida
b = np.random.randint(0, 10, (3, 3)) #butun sonlar

a
b

array([[7, 2, 5],
       [4, 1, 7],
       [5, 1, 4]])

In [ ]:
#Attributelar

arr = np.array([[14, 7, 3], [7, 5, 6]])

print(arr.shape) # (2, 3) - 2 qator, 3 ustun
print(arr.ndim) # 2- ikki o'chamli
print(arr.size) # 6 - jami element soni
print(arr.dtype) # int64 - element turi

(2, 3)
2
6
int64


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
arr[0] # 10
arr[-1] # 50
arr[1:4] # [20, 30, 40]
arr[::2] # [10, 30, 50]
np.random.seed(42)
arr2 = np.random.randint(0, 11, (3, 2))
print(arr2)
print(arr2[0:3, 1])

[[ 6  3]
 [10  7]
 [ 4  6]]
[3 7 6]


In [ ]:
#Statistik funksiyalar

arr = np.array([4, 5, 12, 14, 20])

print(np.sum(arr)) #umumiy qiymat
print(np.mean(arr)) # o'rtacha qiymat
print(np.std(arr)) # standart og'ish
print(np.min(arr)) # eng kichik qiymat
print(np.max(arr)) # eng katta qiymat
print(np.argmax(arr)) #maksimal element indeksi

55
11.0
5.932958789676531
4
20
4


In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/talabalar - talabalar.csv.csv")

In [ ]:
df

,ism,yosh,shahar,fan,baho,kurs
0,Hulkar Mirzayeva,23,Farg'ona,Geografiya,98,3
1,Jasur Holiqov,22,Termiz,Iqtisodiyot,97,1
2,Feruza Nazarova,25,Andijon,Adabiyot,66,1
3,Sherzod Tursunov,19,Andijon,Adabiyot,66,2
4,Lola Xudoyberdiyeva,24,Toshkent,Geografiya,97,3
...,...,...,...,...,...,...
95,Kamola Normatova,24,Jizzax,Geografiya,80,1
96,Feruza Nazarova,26,Samarkand,Biologiya,70,3
97,Mansur Qosimov,24,Jizzax,Fizika,74,4
98,Barno Hamidova,22,Nukus,Tarix,74,3


In [ ]:
df.head()


,ism,yosh,shahar,fan,baho,kurs
0,Hulkar Mirzayeva,23,Farg'ona,Geografiya,98,3
1,Jasur Holiqov,22,Termiz,Iqtisodiyot,97,1
2,Feruza Nazarova,25,Andijon,Adabiyot,66,1
3,Sherzod Tursunov,19,Andijon,Adabiyot,66,2
4,Lola Xudoyberdiyeva,24,Toshkent,Geografiya,97,3


In [ ]:
df.tail()

,ism,yosh,shahar,fan,baho,kurs
95,Kamola Normatova,24,Jizzax,Geografiya,80,1
96,Feruza Nazarova,26,Samarkand,Biologiya,70,3
97,Mansur Qosimov,24,Jizzax,Fizika,74,4
98,Barno Hamidova,22,Nukus,Tarix,74,3
99,Jasur Holiqov,20,Samarkand,Geografiya,65,1


In [ ]:
df.describe()

,yosh,baho,kurs
count,100.000000,100.000000,100.000000
mean,22.600000,77.080000,2.420000
std,2.651472,13.786745,1.147505
min,18.000000,55.000000,1.000000
25%,20.750000,65.000000,1.000000
50%,23.000000,77.500000,2.000000
75%,25.000000,89.500000,3.250000
max,26.000000,100.000000,4.000000


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   ism     100 non-null    object
 1   yosh    100 non-null    int64 
 2   shahar  100 non-null    object
 3   fan     100 non-null    object
 4   baho    100 non-null    int64 
 5   kurs    100 non-null    int64 
dtypes: int64(3), object(3)
memory usage: 4.8+ KB


In [ ]:
df.shape

(100, 6)

In [ ]:
df.isnull().sum()

,0
ism,0
yosh,0
shahar,0
fan,0
baho,0
kurs,0


In [ ]:
!pip install opendatasets

In [ ]:
import opendatasets as od
od.download("https://www.kaggle.com/competitions/titanic/data")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds


In [ ]:
df2 = pd.read_csv("/content/parental_genetics_child_traits.csv")

In [ ]:
df2.isnull().sum()

In [ ]:
df2.dropna(axis=1, inplace = True)

In [ ]:
df2.isnull().sum()

In [ ]:
# Bitta ustun (Series)
df['ism']
# Bir necha ustun
df[['ism', 'baho']]
# Yangi ustun qo'shish
df['daraja'] = df['baho'] / 10
# # Ustun o'chirish
df.drop('daraja', axis=1)


In [ ]:
# Baho 80 dan yuqori
df[df['baho'] > 80]


In [ ]:
df3 = df[df['baho'] > 80]
df3.sum()

In [ ]:
#Qo'shimcha dars
# 3x3 nol masssiv
#2x2 birlik massiv
#

arr = np.zeros((3, 3))

#problem-1
data = np.array([
    [17, 4.0, 1],
    [18, 3.5, 0],
    [16, 4.5, 1],
    [19, 2.8, 0]
])

print(data.shape)
print(data[:, 0])
print(data[:, 1])
print(data[0])
print(data[:-1])

In [ ]:
#problem-2
arr = np.arange(1, 51)
arr

In [ ]:
#problem-3

scores = [72, 81, 65, 90, 77]
arr = np.array(scores) + 5
print(arr)
print(arr.mean())
print(arr.max())

In [ ]:
#problem-4
revenue = [120, 150, 130, 200, 175]
arr = np.array(revenue)
increase = arr + (arr * 0.1)
print(increase)
print(arr.sum())
print(arr.mean())

In [ ]:
#problem-5
students = {
    "Name": ["Ali", "Vali", "Salim", "Aziza", "Madina"],
    "Score": [88, 75, 92, 67, 95]
}
df = pd.DataFrame(students)
print(df)
print(df["Name"])
print(df["Score"].mean())
print(df[df["Score"] > 80])
df["Name"]


In [ ]:
#problem-6
sales = {
    "Product": ["Latte", "Espresso", "Cappuccino", "Americano"],
    "Sold": [120, 200, 150, 90]
}

sales_t = pd.DataFrame(sales)
sales_t

maximum = sales_t["Sold"].idxmax()
print(maximum)
highest = sales_t["Product"][maximum]
print(highest)
# print(sales_t["Sold"].sum())
sales_t[sales_t["Sold"] > 100]