<a href="https://colab.research.google.com/github/mokhivibes/ml_course_courseworks/blob/main/NumpyFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# The start of NumPy lesson of BroCode
# Numpy Fundamentals

In [3]:
import numpy as np
print(np.__version__) #=> prints current version

2.0.2


In [4]:
array = np.array([1, 2, 3, 4])

array = array * 2

print(array)

print(type(array))

[2 4 6 8]
<class 'numpy.ndarray'>


In [5]:
array = np.array('A') #=> 0 dimenstional array
print(array.ndim)

array = np.array(['A', 'B', 'C']) #=> 1 dimenstional array
print(array.ndim)

array = np.array([['A', 'B', 'C'],
                  ['D', 'E', 'F'],
                  ['G', 'H', 'I'] ]) #=> 2 dimenstional array
print(array.ndim)

array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                  [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                  [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', '_']]])
print(array.ndim)

print(array.shape)
# 1 => number of depth
# 2 => number of rows
# 3 => number of columns

0
1
2
3
(3, 3, 3)


In [6]:
print(array[0, 0, 2])

my_name = array[1, 1, 0] + array[1, 1, 2] + array[1, 0, 1] + array[0, 2, 1] + array[0, 2, 2]
print(my_name)

C
MOKHI


In [7]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

# array[start:end:step] => how to slice the array

print(array[::2])
print(array[:3])
print(array[::-1]) # reverse order

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [8]:
#Scalar arithmetic

array = np.array([1, 2, 3])

print(array + 1)
print(array - 2)
print(array * 3)
print(array / 4)
print(array ** 5)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [9]:
#Vectorized math funcs

array = np.array([1.019, 2.56, 3.199])

print(np.sqrt(array)) # ildizdan chiqaradi
print(np.round(array, 2)) # removes numbers at the end and yaxlitlaydi
print(np.floor(array)) # gets the lower
print(np.ceil(array)) # => gets the higher
print(np.pi)


[1.0094553  1.6        1.78857485]
[1.02 2.56 3.2 ]
[1. 2. 3.]
[2. 3. 4.]
3.141592653589793


In [10]:
#EXERCISE

radii = np.array([1, 2, 3])

print(np.pi * radii ** 2)

[ 3.14159265 12.56637061 28.27433388]


In [11]:
#Element-wise arithmetic

array1 = np.array([1, 2, 3])
array2= np.array([4, 5, 6])

print(array1 + array2)
print(array1 - array2)
print(array1 / array2)
print(array1 * array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[ 4 10 18]
[  1  32 729]


In [12]:
#Comparison operators

scores = np.array([91, 55, 100, 73, 82, 64])

print(scores == 100)

print(scores >= 60)

print(scores < 60)

scores[scores < 60] = 0
print(scores)

[False False  True False False False]
[ True False  True  True  True  True]
[False  True False False False False]
[ 91   0 100  73  82  64]


In [13]:
# Broadcasting allows NumPy to perform
#operations on arrays with different shapes by
#virtually expamding dimensions so they match the
#larger array's shapes by virtually expanding
#dimensions so they match the larger array's shape.

# The dimensions have the same size.
#OR
# One of the dimensions has a size of 1

In [14]:
array1 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 15]])
array2 = np.array([[1], [2], [3], [4]])

print(array1.shape)
print(array2.shape)

print(array1 * array2)

(4, 4)
(4, 1)
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 60]]


In [15]:
array1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8 , 9 , 10]])
array2 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])

print(array1.shape)
print(array2.shape)
print(array1 * array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [16]:
#Extra tasks:

#1. Create a 1D array of numbers 0–9, then reverse it without using a loop.
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [19]:
#2. Create a 5x5 array of zeros, then set the border (first/last row and column) to 1

array = np.zeros((5, 5))
array[0, :] = 1
array[:, 0] = 1
array[4, :] = 1
array[:, 4] =1
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
#3. Given a 1D array, extract every other element using slicing.
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array[::2])

[0 2 4 6 8]


In [24]:
 #4. Create a 3x3 identity-like array manually (without np.eye) using indexing.
array = np.zeros((3, 3))

array[0, 0] = 1
array[1, 1] = 1
array[2, 2] = 1

print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
#5. Take a 1D array of 12 elements and reshape it into a (3,4) array, then into a (4,3) array.


array1 = np.array([[0, 1, 2, 3],
                 [4, 5, 6, 7],
                 [8, 9, 10, 11]])
print(array)

array2 = np.array([[0, 1, 2],
                 [3, 4, 5],
                 [6, 7, 8],
                 [9, 10, 11]])
print(array)



array3 = np.arange(12)
print(array3)
array_3x4 = array3.reshape(3,4)
array_4x3 = array3.reshape(4, 3)

print(array_3x4)
print(array_4x3)





[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [44]:
#6 Flatten a 2D array back into 1D without using .flatten() (hint: .reshape(-1)).

array = np.zeros((3, 2))
array_1d = array.reshape(-1)
print(array)
print(array_1d)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[0. 0. 0. 0. 0. 0.]


In [50]:
#7. Given a (3,3) matrix, add [10, 20, 30] to every row using broadcasting.

array = np.arange(9).reshape(3, 3)
array1 = np.array([10, 20, 30])
array_m = array * array1
array_a = array + array1

print(array_m)
print(array_a)

[[  0  20  60]
 [ 30  80 150]
 [ 60 140 240]]
[[10 21 32]
 [13 24 35]
 [16 27 38]]


In [58]:
#8. Given a (3,3) matrix, add [[10],[20],[30]] to every column using broadcasting.

matrix = np.zeros((3, 3))
row_vector = np.array([[10], [20], [30]])
ready_arr = matrix + row_vector
print(ready_arr)


[[10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


In [62]:
#9. Create a multiplication table (1–10 x 1–10) using only broadcasting (no loops) — hint: multiply a column vector by a row vector.

array1 = np.arange(1, 11).reshape(10, 1)
array2 = np.arange(1, 11).reshape(1, 10)
print(array1)
print(array2)
print(array1 * array2)


[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[ 1  2  3  4  5  6  7  8  9 10]]
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [64]:
#10. Given temperatures in Celsius as a 1D array, convert to Fahrenheit using a formula and broadcasting.

celsius = np.array([0,10,25,32,50,100])
fahrenheit =(celsius * 9)/5 + 32
print(fahrenheit)

[ 32.   50.   77.   89.6 122.  212. ]


In [73]:
#11. Center a 2D array's columns (subtract the mean of each column from that column) using broadcasting.
array = np.arange(6).reshape(2, 3)
mean =array.mean(axis=0)
print(array)
print(mean)
print(array - mean)

[[0 1 2]
 [3 4 5]]
[1.5 2.5 3.5]
[[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]


In [85]:
#12.  Given two 1D arrays of different lengths reshaped appropriately, compute their outer sum (every pairwise sum) without loops.


array1 = np.arange(6).reshape(6, 1)
array2 = np.arange(12)
sum = array1 + array2
print(sum)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 2  3  4  5  6  7  8  9 10 11 12 13]
 [ 3  4  5  6  7  8  9 10 11 12 13 14]
 [ 4  5  6  7  8  9 10 11 12 13 14 15]
 [ 5  6  7  8  9 10 11 12 13 14 15 16]]


In [92]:
# Aggregate functions = summarize data and typically return a single value

array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10]])

print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))
print(np.min(array))
print(np.max(array))
print(np.argmin(array))
print(np.argmax(array))

#Sum of the columns:

print(np.sum(array, axis=0))

#Sum of the rows

print(np.sum(array, axis=1))


55
5.5
2.8722813232690143
8.25
1
10
0
9
[ 7  9 11 13 15]
[15 40]


In [108]:
# Filtering = refers to the process of selcting elements from an array that match a given condition

ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65],
                 [39, 22, 15, 99, 18, 19, 20, 21]])

teenagers = ages[ages < 18]
print(teenagers)

adults = ages[(ages >= 18) & (ages < 65)] # => and sign is &
print(adults)

adults = ages[(ages < 18) | (ages >= 65)] # => or sign is |
print(adults)

seniors = ages[ages >= 65]
print(seniors)

evens = ages[ages % 2 == 0]
print(evens)

odds = ages[ages % 2 != 0]
print(odds)

adults = np.where(ages >= 18, ages, 0)
print(adults)


teenagers = np.where(ages < 18, ages, -1)
print(teenagers)

seniors = np.where(ages >= 65, ages, 2)
print(seniors)

evens = np.where(ages % 2 == 0, ages, 3)
print(evens)

[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]
[17 16 65 15 99]
[65 99]
[20 16 30 18 22 18 20]
[21 17 19 65 39 15 99 19 21]
[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]
[[-1 17 -1 -1 16 -1 -1 -1]
 [-1 -1 15 -1 -1 -1 -1 -1]]
[[ 2  2  2  2  2  2  2 65]
 [ 2  2  2 99  2  2  2  2]]
[[ 3  3  3 20 16 30 18  3]
 [ 3 22  3  3 18  3 20  3]]


In [126]:
# Generate random numbers
np.random.seed(42)
rng = np.random.default_rng(seed = 1)
print(rng.integers(low = 1, high = 101, size = (3, 4)))

#Generate random floating numbers

print(np.random.uniform(low=-1, high=1, size = (3,2)))

[[48 52 76 96]
 [ 4 15 83 95]
 [25 32 87 43]]
[[-0.25091976  0.90142861]
 [ 0.46398788  0.19731697]
 [-0.68796272 -0.68801096]]


In [133]:
# Shuffle array
rng = np.random.default_rng()
array = np.array([1, 2, 3, 4, 5])
rng.shuffle(array)
print(array)


[4 1 2 5 3]


In [139]:
# Random choice

rng = np.random.default_rng()

fruits = ["🍏", "🍌", "🍒", "🥥", "🍍"]
fruits = rng.choice(fruits, size=(3, 3))
print(fruits)


[['🍒' '🍒' '🍒']
 ['🍌' '🍌' '🍍']
 ['🍌' '🍏' '🍌']]


In [ ]:
#The end of NumPy lesson of BroCode